insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'ac est', 'volutpat convallis morbi odio odio elementum', 'approved', 88, 6);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'congue diam id', 'vulputate justo in blandit ultrices', 'pending', 68, 81);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'turpis donec posuere metus vitae ipsum aliquam', 'ut erat id mauris vulputate elementum', 'pending', 58, 32);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'odio consequat varius integer ac leo', 'ante', 'denied', 77, 46);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'vel accumsan tellus nisi eu', 'curae mauris viverra', 'approved', 63, 0);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'maecenas leo odio condimentum id', 'sapien cursus vestibulum proin eu', 'approved', 28, 2);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'sem fusce consequat nulla nisl nunc', 'eleifend luctus ultricies', 'approved', 63, 57);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'nullam porttitor lacus at turpis donec', 'fermentum justo nec condimentum neque sapien', 'pending', 91, 76);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'ante vestibulum ante ipsum primis in', 'gravida', 'pending', 50, 78);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'ligula sit amet eleifend', 'in faucibus orci luctus et', 'approved', 47, 28);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'nam tristique tortor eu', 'et eros vestibulum ac est lacinia nisi', 'denied', 99, 62);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'donec ut', 'pede ac diam cras pellentesque volutpat', 'approved', 80, 27);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'luctus et', 'tincidunt lacus at velit', 'approved', 23, 40);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'morbi', 'leo maecenas pulvinar lobortis', 'denied', 30, 25);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'interdum mauris', 'lectus suspendisse potenti in eleifend', 'approved', 37, 42);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'pretium quis lectus', 'tincidunt nulla mollis', 'approved', 6, 41);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'erat vestibulum', 'luctus et ultrices posuere cubilia curae', 'denied', 4, 48);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'fermentum donec ut mauris', 'lobortis sapien sapien non mi integer', 'approved', 57, 59);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'nisl aenean', 'aenean fermentum donec ut mauris eget massa', 'pending', 72, 70);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'enim sit', 'ligula nec sem duis aliquam convallis nunc', 'pending', 92, 32);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'in imperdiet et commodo vulputate justo in', 'pellentesque quisque porta volutpat', 'pending', 34, 71);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'luctus cum sociis natoque penatibus et', 'nulla ultrices', 'denied', 51, 31);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'quam turpis adipiscing lorem vitae mattis nibh', 'rutrum ac lobortis vel dapibus at diam', 'approved', 68, 89);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'tortor duis', 'orci mauris lacinia sapien', 'denied', 49, 28);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'amet nunc viverra dapibus', 'eget rutrum at', 'denied', 71, 88);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'blandit', 'elementum eu interdum eu tincidunt in', 'denied', 66, 29);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'etiam vel augue vestibulum rutrum rutrum', 'ultrices', 'denied', 83, 13);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'cras', 'maecenas ut massa quis augue', 'denied', 3, 97);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'tincidunt ante vel ipsum praesent', 'dapibus', 'approved', 16, 7);
insert into Requests (setlist_id, song_artist, song_title, status, votes_up, votes_down) values (5, 'ante ipsum primis in faucibus', 'feugiat et eros vestibulum ac est lacinia', 'denied', 84, 38);
